/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vimjGEJLo1b
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function LandingPage() {
  return (
    <div key="1" className="flex flex-col min-h-[100dvh]">
      <header className="flex items-center px-4 h-14 lg:px-6">
        <Link className="flex justify-center items-center" href="#">
          <CodeIcon className="w-6 h-6" />
          <span className="sr-only">Zukauskas.dev Portfolio</span>
        </Link>
        <nav className="flex gap-4 ml-auto sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Skills
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Projects
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full h-screen py-12 md:py-24 lg:py-32 xl:py-48 bg-[url('/bg-image.jpg')] bg-cover bg-center flex justify-center items-center">
          <div className="container flex flex-col items-center justify-center px-4 md:px-6 gap-2">
            <div className="flex flex-col items-center p-6 space-y-4 text-center rounded-xl bg-black/50 bg-clip-padding backdrop-blur-sm shadow-xl md:p-10">
              <div className="space-y-2">
                <h1 className="text-4xl font-bold tracking-tighter text-blue-500 sm:text-5xl md:text-6xl lg:text-7xl">Tautvydas Žukauskas</h1>
                <h2 className="text-2xl font-semibold text-gray-500 md:text-3xl">Web Developer</h2>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl ">
                  I'm a passionate web developer with a burning desire to create innovative and user-friendly web applications using AI.
                </p>
              </div>
            </div>
            <div className="mouse-icon"></div>
          </div>
        </section>
        <section className="py-12 w-full bg-gray-100 md:py-24 lg:py-32" id="skills">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col justify-center items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block px-3 py-1 text-sm bg-gray-100 rounded-lg">My Skills</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Expertise and Capabilities
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  I have a diverse set of skills that allow me to create high-quality web applications. From front-end
                  development to back-end integration, I'm proficient in the latest technologies and frameworks.
                </p>
              </div>
            </div>
            <div className="grid gap-6 items-center py-12 mx-auto max-w-5xl lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Front-end Development</h3>
                <p className="text-gray-500 d">
                  Expertise in HTML, CSS, JavaScript, and modern front-end frameworks like React, Vue, and Angular.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Back-end Development</h3>
                <p className="text-gray-500">
                  Proficient in server-side technologies such as Node.js, Python, and PHP, with experience in building
                  RESTful APIs and integrating databases.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">UI/UX Design</h3>
                <p className="text-gray-500">
                  Skilled in creating visually appealing and user-friendly interfaces, with a keen eye for design and a
                  focus on accessibility.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 w-full md:py-24 lg:py-32" id="projects">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col justify-center items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block px-3 py-1 text-sm bg-gray-100 rounded-lg">
                  My Projects
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Showcasing My Work</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
                  Take a look at some of the web applications and projects I've worked on. These showcase my skills and
                  the diverse range of technologies I've mastered.
                </p>
              </div>
            </div>
            <div className="grid gap-6 items-center py-12 mx-auto max-w-5xl lg:grid-cols-2 lg:gap-12">
              <div className="overflow-hidden relative rounded-xl group">
                <img
                  alt="Project 1"
                  className="object-cover object-center overflow-hidden mx-auto transition-all duration-300 aspect-video group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 p-6 opacity-0 transition-all duration-300 bg-gray-900/80 group-hover:opacity-100">
                  <div className="flex flex-col justify-between h-full">
                    <div>
                      <h3 className="text-2xl font-bold text-gray-50">Project 1</h3>
                      <p className="mt-2 text-gray-300">
                        A modern and responsive web application built with React and Firebase.
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Link
                        className="inline-flex justify-center items-center px-4 h-9 text-sm font-medium text-gray-900 bg-gray-50 rounded-md shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        View Project
                      </Link>
                      <Link
                        className="inline-flex justify-center items-center px-4 h-9 text-sm font-medium bg-white rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        GitHub
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
              <div className="overflow-hidden relative rounded-xl group">
                <img
                  alt="Project 2"
                  className="object-cover object-center overflow-hidden mx-auto transition-all duration-300 aspect-video group-hover:scale-105"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
                <div className="absolute inset-0 p-6 opacity-0 transition-all duration-300 bg-gray-900/80 group-hover:opacity-100">
                  <div className="flex flex-col justify-between h-full">
                    <div>
                      <h3 className="text-2xl font-bold text-gray-50">Project 2</h3>
                      <p className="mt-2 text-gray-300">
                        A e-commerce website built with Next.js and Stripe integration.
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Link
                        className="inline-flex justify-center items-center px-4 h-9 text-sm font-medium text-gray-900 bg-gray-50 rounded-md shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        View Project
                      </Link>
                      <Link
                        className="inline-flex justify-center items-center px-4 h-9 text-sm font-medium bg-white rounded-md border border-gray-200 shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        GitHub
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 w-full bg-gray-100 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col justify-center items-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block px-3 py-1 text-sm bg-gray-100 rounded-lg">
                  Get in Touch
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Let's Collaborate</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed ">
                  I'm always excited to work on new projects and connect with fellow developers. Feel free to reach out
                  to me using the form below, and I'll get back to you as soon as possible.
                </p>
              </div>
              <div className="mx-auto space-y-2 w-full max-w-sm">
                <form className="flex flex-col space-y-4">
                  <Input className="flex-1 max-w-lg" placeholder="Your Name" type="text" />
                  <Input className="flex-1 max-w-lg" placeholder="Your Email" type="email" />
                  <Textarea className="flex-1 max-w-lg" placeholder="Your Message" />
                  <Button className="w-full" type="submit">
                    Send Message
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 items-center px-4 py-6 w-full border-t sm:flex-row shrink-0 md:px-6">
        <p className="text-xs text-gray-500">© 2024 John Doe. All rights reserved.</p>
        <nav className="flex gap-4 sm:ml-auto sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CodeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}
