'use client'
import Terminal from "./Terminal";

export function LandingPage() {
   const messages = [
     "Starting...",
     "Reached target Local Encrypted Volumes.",
     "Reached target Initrd Root Device.",
     "Reached target System Initialization.",
     "Reached target Basic System.",
     "Mounting /sysroot...",
     "Mounting /sysroot/run...",
     "Mounting /sysroot/dev...",
     "Mounting /sysroot/proc...",
     "Mounting /sysroot/tmp...",
     "Mounting /sysroot/var...",
     "Mounting /sysroot/home...",
     "Mounting /sysroot/boot...",
     "Mounting /sysroot/media...",
     "Mounting /sysroot/mnt...",
     "Mounting /sysroot/opt...",
     "Mounting /sysroot/srv...",
     "Mounting /sysroot/usr...",
     "Mounting /sysroot/lib...",
     "Mounting /sysroot/etc...",
     "Mounting /sysroot/lib64...",
     "Mounting /sysroot/libx32...",
     "Mounting /sysroot/usr/local...",
     "Reached target Local File Systems.",
     "Reached target System Time.",
     "Reached target Network.",
     "Reached target Network Time.",
     "Reached target Remote File Systems.",
     "Reached target User Environment.",
     "Reached target Login Prompts.",
     "Reached target Graphical Interface.",
     "Reached target Default.",
     "Starting user services...",
     "Starting X server...",
     "Starting display manager...",
     "Starting desktop environment...",
     "Starting applications...",
     "Starting services...",
     "Starting daemons...",
     "Starting processes...",
     "Starting threads...",
     "Starting tasks...",
     "Starting jobs...",
     "Starting scripts...",
     "Starting programs...",
     "Starting modules...",
     "Starting drivers...",
     "Starting devices...",
     "Starting hardware...",
     "Starting firmware...",
     "Starting system...",
     "Starting kernel...",
     "Starting boot loader...",
     "Starting BIOS...",
     "Starting CPU...",
     "Starting RAM...",
     "Starting hard drive...",
     "Starting network card...",
     "Starting graphics card...",
     "Starting sound card...",
     "Starting mouse...",
     "Starting keyboard...",
     "Starting monitor...",
     "Starting printer...",
     "Starting scanner...",
     "Starting webcam...",
     "Starting microphone...",
     "Starting speakers...",
     "Starting headphones...",
     "Starting USB...",
     "Starting Bluetooth...",
     "Starting WiFi...",
     "Starting Ethernet...",
     "Starting modem...",
     "Starting router...",
     "Starting switch...",
     "Starting hub...",
     "Starting server...",
     "Starting client...",
     "Starting application...",
     "Starting program...",
     "Starting script...",
     "Starting task...",
     "Starting job...",
     "Starting thread...",
     "Starting process...",
     "Starting daemon...",
     "Starting service...",
     "Starting environment...",
     "Starting user...",
     "Starting system...",
     "Starting boot...",
     "Starting init...",
     "Starting kernel...",
     "Starting BIOS...",
     "Starting CPU...",
     "Starting RAM...",
     "Starting hard drive...",
     "Starting network card...",
     "Starting graphics card...",
     "Starting sound card...",
     "Starting mouse...",
     "Starting keyboard...",
     "Starting monitor...",
     "Starting printer...",
     "Starting scanner...",
     "Starting webcam...",
     "Starting microphone...",
     "Starting speakers...",
     "Starting headphones...",
     "Starting USB...",
     "Starting Bluetooth...",
     "Starting WiFi...",
     "Starting Ethernet...",
     "Starting modem...",
     "Starting router...",
     "Starting switch...",
     "Starting hub...",
     "Starting server...",
     "Starting client...",
     "Starting application...",
     "Starting program...",
     "Starting script...",
     "Starting task...",
     "Starting job...",
     "Starting thread...",
     "Starting process...",
     "Starting daemon...",
     "Starting service...",
     "Starting environment...",
     "Starting user...",
   ];

  return (
    <Terminal messages={messages} />
  );
}
